cmd_/users/stud16/openv/openvswitch-1.1.0pre2/datapath/linux-2.6/ip_output-openvswitch.o :=  gcc-4.3 -Wp,-MD,/users/stud16/openv/openvswitch-1.1.0pre2/datapath/linux-2.6/.ip_output-openvswitch.o.d  -nostdinc -isystem /usr/lib/gcc/i486-linux-gnu/4.3.5/include -I/users/stud16/openv/openvswitch-1.1.0pre2/datapath/linux-2.6/compat-2.6 -I/users/stud16/openv/openvswitch-1.1.0pre2/datapath/linux-2.6/compat-2.6/include  -Iinclude -Iinclude2 -I/usr/src/linux-headers-2.6.32-5-common/include -I/usr/src/linux-headers-2.6.32-5-common/arch/x86/include -include include/linux/autoconf.h   -I/users/stud16/openv/openvswitch-1.1.0pre2/datapath/linux-2.6 -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -m32 -msoft-float -mregparm=3 -freg-struct-return -mpreferred-stack-boundary=2 -march=i686 -mtune=generic -Wa,-mtune=generic32 -ffreestanding -fstack-protector -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -fomit-frame-pointer -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -DVERSION=\"1.1.0pre2\"   -I/users/stud16/openv/openvswitch-1.1.0pre2/datapath/linux-2.6/..   -I/users/stud16/openv/openvswitch-1.1.0pre2/datapath/linux-2.6/..   -I/users/stud16/openv/openvswitch-1.1.0pre2/include -DBUILDNR=\"\" -g -include /users/stud16/openv/openvswitch-1.1.0pre2/datapath/linux-2.6/kcompat.h  -DMODULE -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(ip_output_openvswitch)"  -D"KBUILD_MODNAME=KBUILD_STR(openvswitch_mod)"  -c -o /users/stud16/openv/openvswitch-1.1.0pre2/datapath/linux-2.6/.tmp_ip_output-openvswitch.o /users/stud16/openv/openvswitch-1.1.0pre2/datapath/linux-2.6/ip_output-openvswitch.c

deps_/users/stud16/openv/openvswitch-1.1.0pre2/datapath/linux-2.6/ip_output-openvswitch.o := \
  /users/stud16/openv/openvswitch-1.1.0pre2/datapath/linux-2.6/ip_output-openvswitch.c \
  /users/stud16/openv/openvswitch-1.1.0pre2/datapath/linux-2.6/kcompat.h \
  include/linux/version.h \

/users/stud16/openv/openvswitch-1.1.0pre2/datapath/linux-2.6/ip_output-openvswitch.o: $(deps_/users/stud16/openv/openvswitch-1.1.0pre2/datapath/linux-2.6/ip_output-openvswitch.o)

$(deps_/users/stud16/openv/openvswitch-1.1.0pre2/datapath/linux-2.6/ip_output-openvswitch.o):
